Docker and devcontainer updated to make more robust (#81)
Via MS Copilot suggestions

Co-authored-by: Holger Berg <36001578+ogierMontanus@users.noreply.github.com>

diff --git a/.devcontainer/Dockerfile.dev b/.devcontainer/Dockerfile.dev
--- a/.devcontainer/Dockerfile.dev
+++ b/.devcontainer/Dockerfile.dev
@@ -1,5 +1,9 @@
+# syntax=docker/dockerfile:1
 FROM mcr.microsoft.com/devcontainers/java:11-bullseye
 
+# -----------------------------
+# Versions / ports
+# -----------------------------
 ARG EXIST_VERSION=6.2.0
 ARG TEMPLATING_VERSION=1.1.0
 ARG PUBLISHER_LIB_VERSION=4.0.0
@@ -9,67 +13,81 @@ ARG EDITOR_VERSION=1.1.0
 ARG HTTP_PORT=8080
 ARG HTTPS_PORT=8443
 
-RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
-    && apt-get -y install --no-install-recommends bzip2
+# -----------------------------
+# Remove Yarn apt repo added by devcontainer tooling (prevents GPG failures)
+# -----------------------------
+RUN rm -f /etc/apt/sources.list.d/yarn.list \
+    && rm -f /usr/share/keyrings/yarnkey.gpg \
+    && rm -f /etc/apt/trusted.gpg.d/yarn.gpg || true
 
-# Install Ant for building TEI Publisher libraries
+# -----------------------------
+# Base system packages
+# -----------------------------
+RUN apt-get update \
+    && export DEBIAN_FRONTEND=noninteractive \
+    && apt-get -y install --no-install-recommends \
+        bzip2 \
+        ca-certificates \
+        curl \
+        git \
+        gnupg \
+        python3-pip \
+    && pip3 install --upgrade pip \
+    && rm -rf /var/lib/apt/lists/*
+
+# -----------------------------
+# Ant via SDKMAN (as vscode user)
+# -----------------------------
 RUN su vscode -c "source /usr/local/sdkman/bin/sdkman-init.sh && sdk install ant"
 ENV ANT_HOME=/usr/local/sdkman/candidates/ant/current
-ENV PATH=${PATH}:${ANT_HOME}/bin
+ENV PATH="${PATH}:${ANT_HOME}/bin"
 
-# [Option] Install Node.js
-ARG INSTALL_NODE="true"
-ARG NODE_VERSION="lts/*"
-RUN if [ "${INSTALL_NODE}" = "true" ]; then su vscode -c "source /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi
-
-# Install python pip and upgrade it to latest version
-RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
-    && apt-get -y install --no-install-recommends bzip2 \
-    && apt-get -y install --no-install-recommends python3-pip \
-    && pip3 install --upgrade pip
-
-# [Optional] Uncomment this line to install global node packages.
-# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
-
+# -----------------------------
+# Workspace
+# -----------------------------
 WORKDIR /workspaces
 
-# Download and install eXist-db
-RUN curl -L -o exist-distribution-${EXIST_VERSION}-unix.tar.bz2 https://github.com/eXist-db/exist/releases/download/eXist-${EXIST_VERSION}/exist-distribution-${EXIST_VERSION}-unix.tar.bz2 \
-    && tar xfj exist-distribution-${EXIST_VERSION}-unix.tar.bz2 -C /usr/local \
-    && rm exist-distribution-${EXIST_VERSION}-unix.tar.bz2 \
-    && mv /usr/local/exist-distribution-${EXIST_VERSION} /usr/local/exist
+# -----------------------------
+# Install eXist-db
+# -----------------------------
+RUN curl -L -o "exist-${EXIST_VERSION}.tar.bz2" \
+        "https://github.com/eXist-db/exist/releases/download/eXist-${EXIST_VERSION}/exist-distribution-${EXIST_VERSION}-unix.tar.bz2" \
+    && tar xfj "exist-${EXIST_VERSION}.tar.bz2" -C /usr/local \
+    && rm "exist-${EXIST_VERSION}.tar.bz2" \
+    && mv "/usr/local/exist-distribution-${EXIST_VERSION}" /usr/local/exist
 
-# If tei-publisher-lib version is "master", build it. Otherwise download the specified version.
-RUN if [ "${PUBLISHER_LIB_VERSION}" = "master" ]; then \
-        git clone https://github.com/eeditiones/tei-publisher-lib.git \
-        && cd tei-publisher-lib \
-        && ant \
-        && cp build/*.xar /usr/local/exist/autodeploy; \
-    else \
-        curl -L -o /usr/local/exist/autodeploy/tei-publisher-lib-${PUBLISHER_LIB_VERSION}.xar https://exist-db.org/exist/apps/public-repo/public/tei-publisher-lib-${PUBLISHER_LIB_VERSION}.xar; \
-    fi
+# -----------------------------
+# Preload required XARs
+# -----------------------------
+RUN curl -L -o "/usr/local/exist/autodeploy/tei-publisher-lib-${PUBLISHER_LIB_VERSION}.xar" \
+        "https://exist-db.org/exist/apps/public-repo/public/tei-publisher-lib-${PUBLISHER_LIB_VERSION}.xar" \
+    && curl -L -o "/usr/local/exist/autodeploy/roaster-${ROUTER_VERSION}.xar" \
+        "https://exist-db.org/exist/apps/public-repo/public/roaster-${ROUTER_VERSION}.xar" \
+    && curl -L -o "/usr/local/exist/autodeploy/templating-${TEMPLATING_VERSION}.xar" \
+        "https://exist-db.org/exist/apps/public-repo/public/templating-${TEMPLATING_VERSION}.xar" \
+    && curl -L -o "/usr/local/exist/autodeploy/atom-editor-${EDITOR_VERSION}.xar" \
+        "https://github.com/wolfgangmm/existdb-langserver/raw/master/resources/atom-editor-${EDITOR_VERSION}.xar"
 
-RUN curl -L -o /usr/local/exist/autodeploy/roaster-${ROUTER_VERSION}.xar https://exist-db.org/exist/apps/public-repo/public/roaster-${ROUTER_VERSION}.xar
-RUN curl -L -o /usr/local/exist/autodeploy/templating-${TEMPLATING_VERSION}.xar https://exist-db.org/exist/apps/public-repo/public/templating-${TEMPLATING_VERSION}.xar
-RUN curl -L -o /usr/local/exist/autodeploy/atom-editor-${EDITOR_VERSION}.xar https://github.com/wolfgangmm/existdb-langserver/raw/master/resources/atom-editor-${EDITOR_VERSION}.xar
-
+# -----------------------------
+# Runtime configuration
+# -----------------------------
 WORKDIR /usr/local/exist
-ENV JAVA_HOME=/usr/lib/jvm/msopenjdk-current
 
-RUN bin/client.sh -l --no-gui --xpath "system:get-version()"
+ENV EXIST_HOME=/usr/local/exist
+ENV JAVA_HOME=/usr/lib/jvm/msopenjdk-current
+ENV JVM_MAX_RAM_PERCENTAGE=75.0
+
+ENV JAVA_OPTS="\
+-Djetty.port=${HTTP_PORT} \
+-Djetty.ssl.port=${HTTPS_PORT} \
+-Dfile.encoding=UTF8 \
+-Dsun.jnu.encoding=UTF-8 \
+-XX:+UseG1GC \
+-XX:+UseStringDeduplication \
+-XX:+UseContainerSupport \
+-XX:MaxRAMPercentage=${JVM_MAX_RAM_PERCENTAGE} \
+-XX:+ExitOnOutOfMemoryError"
 
 EXPOSE ${HTTP_PORT} ${HTTPS_PORT} 8001
 
-ENV EXIST_HOME=/usr/local/exist
-ENV JAVA_OPTS \
-    -Djetty.port=${HTTP_PORT} \
-    -Djetty.ssl.port=${HTTPS_PORT} \
-    -Dfile.encoding=UTF8 \
-    -Dsun.jnu.encoding=UTF-8 \
-    -XX:+UseG1GC \
-    -XX:+UseStringDeduplication \
-    -XX:+UseContainerSupport \
-    -XX:MaxRAMPercentage=${JVM_MAX_RAM_PERCENTAGE:-75.0} \ 
-    -XX:+ExitOnOutOfMemoryError
-
-ENTRYPOINT [ "/usr/local/exist/bin/startup.sh" ]
+ENTRYPOINT ["/usr/local/exist/bin/startup.sh"]
